Switch to Github action
trailblazer/trailblazer-rails pull request #118
Opened 2021-12-07 20:17 UTC by seuros

Test rails 7.0.0
Normalize testing suite

2021-12-07 21:20 UTC, apotonick commented on test/dummy/app/concepts/song/contract/form.rb
> +module Song::Contract
This should be named either `Song::Contract::Create` or `Song::Form::Create`.

2021-12-07 21:27 UTC, apotonick requested changes

2021-12-07 21:27 UTC, apotonick commented on trailblazer-rails.gemspec
> +  spec.homepage      = "https://trailblazer.to/gems/trailblazer/2.0/rails.html"
This should be https://trailblazer.to/2.1/docs/trailblazer.html#trailblazer-rails

2021-12-08 12:13 UTC, apotonick requested changes

2021-12-08 12:13 UTC, apotonick commented on test/integration/artists_controller_test.rb
> +    page.must_have_css "h1"
Why are we changing the test here?

2021-12-08 12:13 UTC, apotonick commented on test/integration/songs_controller_test.rb
>    end
Why are we removing this? Isn't that dangerous and almost "wrong"?

2021-12-08 12:13 UTC, apotonick commented on .github/workflows/ci.yml
> +          - rails_6.0
+ Rails 5.2 please!!!!

2021-12-09 22:50 UTC, seuros commented on test/integration/artists_controller_test.rb
> +    page.must_have_css "h1"
new syntax.

2021-12-10 13:29 UTC, apotonick approved these changes

2021-12-10 13:30 UTC, merged